version: '3.9'

services:
  news:
    container_name: api-news

    build:
      context: ..
      dockerfile: deploy/Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8054:8054"
    depends_on:
      - db
    environment:
      - POSTGRES_URL=postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST/$POSTGRES_DB
    command: >-
      wait-for-it -h db -p 5432 -s -- sh -c "
      alembic upgrade head &&
      uvicorn app.main:app --no-server-header --proxy-headers  --workers=1 --host=0.0.0.0 --port=8054 --lifespan on
      "

  redis:
    image: "redis:alpine"
    restart: always
  

  db:
    image: docker.io/library/postgres:15.2-alpine
    restart: unless-stopped
    ports:
      - 5433:5432
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  arq-scheduler-parser:
   container_name: scheduler-parser
   build:
     context: ..
     dockerfile: ./deploy/Dockerfile
   restart: unless-stopped
   env_file:
     - .env
   depends_on:
     - db
     - redis
   command: arq app.cron.worker.WorkerSettings



volumes:
  postgres_data:
