"""add model news


Revision ID: 97abc6fe7486
Revises: 
Create Date: 2025-01-18 10:36:02.233797

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "97abc6fe7486"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "news",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("pub_date", sa.DateTime(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("scraped_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_news_pub_date"), "news", ["pub_date"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_news_pub_date"), table_name="news")
    op.drop_table("news")
    # ### end Alembic commands ###
